### PR TITLE
first proposal for a framework-wide "uncaught" exception handler

### LINKED ISSUE #13: Observable: framework-wide "uncaught"(?) exception handler?
At the moment, if nobody subscribes for exception in Observable, they get lost without any logging or notice. This could potentially lead to hard-to-debug problems.
Should we implement a facility like Javas UncaughtExceptionHandler to get notified about any? dispatched exception, so one could e.g. attach a logger or a debugger breakpoint to it without knowing where exactly the exception is triggered?

### PR DESCRIPTION
**Pull request by michi42**
Fixes #13.

The idea is that Observers which do not implement onException "bounce back" the exceptions delivered to them, which then get intercepted in the dispatcher. The same happens if a handler genuinely throws an exception.

There can be a global exception handler which gets called in these cases, e.g. to log them using slf4j or any other logging framework the application uses. If unset, it defaults to the previous "print to stderr" behaviour.

### CODE REVIEW

File: src/main/java/org/ossgang/commons/observable/DispatchingObservable.java [hunk 1]
```diff
@@ -109,13 +110,23 @@ protected void dispatchException(Throwable newValue, Predicate<Set<SubscriptionO
         DISPATCHER_POOL.submit(() -> {
             try {
                 handler.accept(value);
+            } catch (UnhandledException e) {
+                uncaughtExceptionHandler.accept(e);
```
Comment (andreacalia) [inline src/main/java/org/ossgang/commons/observable/DispatchingObservable.java]: should we also surround these 2 consumers by try-catch? With just print err in this case... :)

**Comment by andreacalia** [comment]
Looks great Michi! I think this is what we miss at the moment :smile:

File: src/main/java/org/ossgang/commons/observable/DispatchingObservable.java (hunk 1 above)
Comment (michi42) [reply src/main/java/org/ossgang/commons/observable/DispatchingObservable.java]: Done. I've also added a null check in the setter, just in case someone tries to be stupid ;-)

**Comment by andreacalia** [comment]
Perfect michi! :smile:
